apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresCust.fullnameOverride }}-secret
type: Opaque
data:
  POSTGRESQL_PASSWORD: {{ "postgres" | b64enc | quote }}
  REPMGR_PASSWORD: {{ "repmgr" | b64enc | quote }}
  POSTGRESQL_DATABASE: "postgres"