apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.myAirflow.fullnameOverride }}-metadata-secret
type: Opaque
data:
  connection: {{ "postgresql://postgres:postgres@postgresql-dev-fz1:5432/airflow" | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.myAirflow.fullnameOverride }}-admin-secret
type: Opaque
stringData:
  username: admin
  password: admin
  email: admin@example.com

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.myAirflow.fullnameOverride }}-minio-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: admin
  AWS_SECRET_ACCESS_KEY: adminadmin
  AWS_ENDPOINT_URL: minio.dev.svc.cluster.local:9000