apiVersion: v2
name: postgresql-ha
description: >
  This chart deploys Postgres-HA.
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql-ha
    version: "15.3.8"
    repository: "https://charts.bitnami.com/bitnami"
    alias: postgresCust