apiVersion: v2
name: my-airflow-wrapper
description: "SRE optimized Airflow"
version: 0.1.0
dependencies:
  - name: airflow
    version: 1.16.0
    repository: "file://charts/airflow"
    alias: myAirflow